version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/out:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
